# ローカルでコンテナを立てて開発する構成
services:
  web:
    image: kojirer-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kojirer-app-local
    env_file:
      - .env.container
    ports:
      - '52600:52600' # backend
      - '52601:52601' # backend websocket
      - '52800:52800' # frontend
      - '5555:5555' # Prisma Studio
    depends_on:
      - db
    volumes:
      - .:/kojirer # ホストマシンと共有してホットリロードできるようにする
    # プロジェクトルートをバインドマウントしている一方、node_modulesはホストと共有したくない
    # tmpfsでマウントしてentrypointで毎回初期化する
    tmpfs:
      - /kojirer/node_modules:exec
      - /kojirer/packages/api/node_modules:exec
      - /kojirer/packages/backend/node_modules:exec
      - /kojirer/packages/frontend/node_modules:exec
    tty: true # コンテナを終了させない
    stdin_open: true # 標準入力を開いたままにする
  db:
    image: postgres:15-alpine
    container_name: kojirer-db-local
    env_file:
      - .env.container
    ports:
      - 5333:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
