version: "3.9"
services:
  web: 
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: ${TARGET:-prod}
    container_name: kojirer
    restart: always
    ports:
      - "52600:52600"
      - "52800:52800"
    depends_on: 
      - db
    volumes:
      - /node_modules
      - .:/kojirer
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
    