packages:
  - packages/*
ignoredBuiltDependencies:
  - '@prisma/client'
onlyBuiltDependencies:
  - '@asyncapi/cli'
  - '@hyperjump/json-pointer'
  - '@hyperjump/json-schema'
  - '@hyperjump/json-schema-core'
  - '@hyperjump/pact'
  - '@prisma/engines'
  - core-js
  - esbuild
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - yarn
