apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-studio
  namespace: default
  labels:
    app: prisma-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prisma-studio
  template:
    metadata:
      labels:
        app: prisma-studio
    spec:
      containers:
        - name: prisma-studio
          image: kojirer:latest
          command: ['npx', 'prisma', 'studio', '--port', '5555', '--browser', 'none']
          ports:
            - containerPort: 5555
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kojirer-env
                  key: DATABASE_URL
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '256Mi'
              cpu: '100m'
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-studio
  namespace: default
  labels:
    app: prisma-studio
spec:
  type: ClusterIP
  selector:
    app: prisma-studio
  ports:
    - name: http
      port: 5555
      targetPort: 5555
      protocol: TCP
