openapi: '3.0.3'

info:
  title: 'Kojirer API'
  version: 0.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/mit-license.php

servers:
  - url: 'https://kojirer.arcircle.f5.si/api'
    description: ローカル環境

paths:
  '/customizes':
    $ref: './paths/customizes.yml#/CustomizesPath'
  '/dons':
    $ref: './paths/dons.yml#/DonsPath'
  '/dons/{id}':
    $ref: './paths/donsID.yml#/DonsIDPath'
  '/price':
    $ref: './paths/price.yml#/PricePath'
  '/dons/cooking':
    $ref: './paths/donsCooking.yml#/DonsCookingPath'
  '/dons/cooked':
    $ref: './paths/donsCooked.yml#/DonsCookedPath'
  '/dons/delivered':
    $ref: './paths/donsDelivered.yml#/DonsDeliveredPath'
  '/dons/cancel':
    $ref: './paths/donsCancel.yml#/DonsCancelPath'
  '/orders/{id}':
    $ref: './paths/ordersID.yml#/OrdersIDPath'
  '/orders':
    $ref: './paths/orders.yml#/OrdersPath'

components:
  schemas:
    Customizes:
      $ref: './components/customize.yml#/Customize'
    Dons:
      $ref: './components/don.yml#/Don'
    Orders:
      $ref: './components/order.yml#/Order'
