openapi: '3.0.3'

info:
  title: 'Kojirer API'
  version: 0.0.0

servers:
  - url: 'http://localhost:52600/api/'

paths:
  '/customizes':
    $ref: './paths/customizes.yml#/CustomizesPath'
  '/dons':
    $ref: './paths/dons.yml#/DonsPath'
  '/dons/{id}':
    $ref: './paths/donsID.yml#/DonsIDPath'
  '/orders/price':
    $ref: './paths/ordersPrice.yml#/OrdersPricePath'
  '/dons/cooking':
    $ref: './paths/donsCooking.yml#/DonsCookingPath'
  '/dons/cooked':
    $ref: './paths/donsCooked.yml#/DonsCookedPath'
  '/dons/deliver':
    $ref: './paths/donsDelivered.yml#/DonsDeliveredPath'
  '/dons/cancel':
    $ref: './paths/donsCancel.yml#/DonsCancelPath'
  '/orders/{id}':
    $ref: './paths/ordersID.yml#/OrdersIDPath'

components:
  schemas:
    Customizes:
      $ref: './components/Customizes.yml#/Customizes'
    Dons:
      $ref: './components/Dons.yml#/Dons'
    Orders:
      $ref: './components/Orders.yml#/Orders'
