name: Backend Tests

on:
  push:
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend-test.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'packages/backend/**'
      - '.github/workflows/backend-test.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run backend tests
        run: npm run test -w packages/backend
