name: CI (Backend)

on:
  push:
    paths:
      - 'packages/backend/**'
      - '.github/workflows/ci-backend.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/backend/**'
      - '.github/workflows/ci-backend.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - uses: actions/setup-node@v3
        with:
          node-version: 22 # 24にすると pnpm install で heap out of memory する
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run backend tests
        run: pnpm --filter backend test
