name: CI (Docker Build)

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - feature/k3s-cd
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: "docker-build-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.FULL_IMAGE }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare image tag
      id: meta
      run: |
        repo_lc="$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
        echo "FULL_IMAGE=ghcr.io/${repo_lc}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image (and push on main/feature branches)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.FULL_IMAGE }}
        target: production
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

    - name: Test Docker image
      if: github.event_name == 'pull_request'
      run: |
        docker run --rm ${{ steps.meta.outputs.FULL_IMAGE }} node --version
