name: CI (Docker Build)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  # PRの場合はPR番号でグループ化、それ以外はブランチ名でグループ化
  group: "docker-build-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.FULL_IMAGE }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare image tag
      id: meta
      run: |
        repo_lc="$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
        echo "FULL_IMAGE=ghcr.io/${repo_lc}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: false  # PRではpushしない
        tags: ${{ steps.meta.outputs.FULL_IMAGE }}
        target: production
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        load: true  # ローカルにロード

    - name: Test Docker image locally
      run: |
        docker run --rm ${{ steps.meta.outputs.FULL_IMAGE }} node --version
        docker run --rm ${{ steps.meta.outputs.FULL_IMAGE }} sh -c "cd /kojirer && node packages/backend/built/index.js --version || echo 'Server check completed'"
